# =====================================================================================================================
# Omid Client Configuration
# =====================================================================================================================

# ---------------------------------------------------------------------------------------------------------------------
# Basic connection parameters to TSO Server
# ---------------------------------------------------------------------------------------------------------------------

# Direct connection to host:port
connectionType: !!org.apache.omid.tso.client.OmidClientConfiguration$ConnType DIRECT
connectionString: "localhost:24758"

# When Omid is working in High Availability mode, two or more replicas of the TSO server are running in primary/backup
# mode. When a TSO server replica is elected as master, it publishes its address through ZK. In order to configure
# the Omid client to access the TSO server in HA mode:
#     1) set 'connectionType' to !!org.apache.omid.tso.client.OmidClientConfiguration$ConnType HA
#     2) set 'connectionString' to the ZK cluster connection string where the server is publishing its address
zkConnectionTimeoutInSecs: 10
# In HA mode, make sure that the next settings match same settings on the TSO server side
zkNamespace: "omid"
zkCurrentTsoPath: "/current-tso"

# ---------------------------------------------------------------------------------------------------------------------
# Communication protocol parameters
# ---------------------------------------------------------------------------------------------------------------------
# TODO: describe these parameters
requestMaxRetries: 5
requestTimeoutInMs: 5000
reconnectionDelayInSecs: 10
retryDelayInMs: 1000
executorThreads: 3

# ---------------------------------------------------------------------------------------------------------------------
# Transaction Manager parameters
# ---------------------------------------------------------------------------------------------------------------------

# Configure whether the TM performs the post-commit actions for a tx (update shadow cells and clean commit table entry)
# before returning to the control to the client (SYNC) or in parallel (ASYNC)
postCommitMode: !!org.apache.omid.tso.client.OmidClientConfiguration$PostCommitMode SYNC

# Conflict analysis level
# Can either be cell level or row level. Default is cell level
conflictDetectionLevel: !!org.apache.omid.tso.client.OmidClientConfiguration$ConflictDetectionLevel CELL


# ---------------------------------------------------------------------------------------------------------------------
#  TLS parameters
# ---------------------------------------------------------------------------------------------------------------------
tlsEnabled: false
